# remote_theme: pages-themes/tactile@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-tactile
title: "Kevin Torres"
description: "Engineering Projects & Research"

# Optional: if you want navigation defined here
nav:
  - name: Home
    link: /
  - name: About Me
    link: /about/
  - name: Resume
    link: /resume/
  - name: Contact
    link: /contact/
