# Site settings
title: "Kevin Torres"
description: "Engineering Projects & Research"

# Disable theme (since you’re hand-coding your HTML + CSS)
theme: null

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Permalink structure (enables pretty URLs)
permalink: /:path/

# Navigation (used for reference if you decide to make dynamic nav later)
nav:
  - name: Home
    link: /
  - name: About Me
    link: /about/
  - name: Resume
    link: /resume/
  - name: Contact
    link: /contact/
